/* eslint-disable @typescript-eslint/no-unused-vars */
import { useState } from 'react'
import { DndContext, closestCenter, type DragEndEvent } from '@dnd-kit/core'
import { SortableContext, arrayMove, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import { toast } from 'sonner'
import { ArrowLeft, BarChart3, Check, CircleHelp, Clock3, GitBranch, Github, Info, LifeBuoy, ListChecks, Plus, RefreshCw, Settings2, ShieldCheck, Sparkles, UserRound, Workflow, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { AppShell } from '@/components/app-shell'
import { PageHeader } from '@/components/ui'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Separator } from '@/components/ui/separator'
import { Textarea } from '@/components/ui/textarea'
import { useAppAuth } from '@/lib/auth'
import type { ActivityEvent, WorkflowDefinition, WorkflowRun, WorkflowStep } from '@/types'

const events: ActivityEvent[] = []
const runs: WorkflowRun[] = []
function StatePanel({ title, description }: { title: string; description: string }) { return <Card className="flex min-h-52 flex-col items-center justify-center gap-3 p-8 text-center"><h2 className="font-display text-xl font-semibold">{title}</h2><p className="max-w-md text-sm leading-6 text-muted-foreground">{description}</p></Card> }
export function AutomationPage() { return <AppShell><PageHeader eyebrow="Automation" title="Automation is not enabled." description="AutoGit does not simulate repository actions. This workspace will show automation only after a real execution service is connected." /><Alert className="max-w-2xl border-primary/20 bg-primary/5"><Workflow className="size-4" /><AlertTitle>Execution service required</AlertTitle><AlertDescription>No local previews, mock runs, or placeholder workflows are available. Connect a real automation provider before actions can be created or run.</AlertDescription></Alert></AppShell> }
function EventRow({ event }: { event: ActivityEvent }) { const Icon = event.type === 'workflow' ? Workflow : event.type === 'sync' ? RefreshCw : event.type === 'account' ? UserRound : GitBranch; return <div className="flex gap-4 border-b border-border py-4 last:border-0"><div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-muted text-primary"><Icon className="size-4" /></div><div className="min-w-0 flex-1"><p className="font-medium">{event.title}</p><p className="mt-1 text-sm text-muted-foreground">{event.description}</p></div><time className="shrink-0 text-xs text-muted-foreground">{event.createdAt}</time></div> }
export function ActivityPage() { return <AppShell><PageHeader eyebrow="Workspace history" title="Activity" description="A readable trail of syncs, previews, and account events." /><Card className="p-5">{events.map((event) => <EventRow key={event.id} event={event} />)}</Card></AppShell> }
function Metric({ label, value, icon: Icon, detail }: { label: string; value: string; icon: typeof GitBranch; detail: string }) { return <Card className="p-5"><div className="flex justify-between text-sm text-muted-foreground"><span>{label}</span><Icon className="size-4 text-primary" /></div><p className="mt-3 font-display text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></Card> }
export function AnalyticsPage() { return <AppShell><PageHeader eyebrow="Signals" title="Analytics" description="A small set of repository signals to decide what needs attention." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Repositories" value="—" icon={GitBranch} detail="Connect GitHub to populate" /><Metric label="Sync rate" value="—" icon={RefreshCw} detail="No live sync data yet" /><Metric label="Health score" value="—" icon={ShieldCheck} detail="Available after sync" /><Metric label="Automation runs" value={String(runs.length)} icon={Workflow} detail="Local workflow previews" /></div><Card className="mt-6 p-5"><div className="flex items-center gap-2"><BarChart3 className="size-4 text-primary" /><h2 className="font-display font-semibold">Activity pattern</h2></div><div className="mt-6 flex h-40 items-end gap-2 border-b border-border">{[34, 52, 28, 70, 44, 82, 60].map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t bg-primary/70" style={{ height: `${height}%` }} /><span className="font-mono text-[10px] text-muted-foreground">{['M', 'T', 'W', 'T', 'F', 'S', 'S'][index]}</span></div>)}</div><p className="mt-4 text-sm text-muted-foreground">Automation analytics are unavailable until a real execution service is connected.</p></Card></AppShell> }
export function NotificationsPage() { const [unread, setUnread] = useState(false); const visible = unread ? events.slice(0, 1) : events; return <AppShell><PageHeader eyebrow="Workspace updates" title="Notifications" description="Keep track of changes that deserve a second look." action={<Button variant="outline" onClick={() => setUnread((value) => !value)}>{unread ? 'Show all' : 'Unread only'}</Button>} /><Card className="p-5">{visible.length ? visible.map((event) => <EventRow key={event.id} event={event} />) : <StatePanel title="You are all caught up" description="There are no unread workspace updates right now." />}</Card></AppShell> }
export function ProfilePage() { const { session, configured, isLoaded } = useAppAuth(); return <AppShell><PageHeader eyebrow="Account" title="Your profile" description="The identity and connection context behind this workspace." /><Card className="max-w-2xl p-6"><div className="flex items-center gap-4"><div className="flex size-14 items-center justify-center rounded-full bg-primary text-primary-foreground"><UserRound /></div><div><h2 className="font-display text-xl font-semibold">{isLoaded ? session?.name ?? 'Preview user' : 'Loading profile…'}</h2><p className="text-sm text-muted-foreground">{session?.email ?? 'Local preview mode'}</p></div></div><Separator className="my-6" /><dl className="grid gap-5 sm:grid-cols-2"><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Auth provider</dt><dd className="mt-1 font-medium">{configured ? 'Clerk' : 'Local preview'}</dd></div><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">GitHub</dt><dd className="mt-1 flex items-center gap-2 font-medium"><Github className="size-4" />Managed separately</dd></div></dl></Card></AppShell> }
const settingsSchema = z.object({ defaultBranch: z.string().trim().min(1, 'Enter a default branch.'), excludedFolders: z.string().trim() })
export function SettingsPage() { const form = useForm<z.infer<typeof settingsSchema>>({ resolver: zodResolver(settingsSchema), defaultValues: { defaultBranch: 'main', excludedFolders: 'node_modules, dist, .env' } }); return <AppShell><PageHeader eyebrow="Workspace preferences" title="Settings" description="Keep automation predictable with a few explicit defaults." /><Card className="max-w-2xl p-6"><form className="grid gap-5" onSubmit={form.handleSubmit((value) => toast.success('Preferences saved', { description: `Default branch: ${value.defaultBranch}` }))}><div><Label htmlFor="default-branch">Default branch</Label><Input id="default-branch" className="mt-2" {...form.register('defaultBranch')} />{form.formState.errors.defaultBranch && <p className="mt-1 text-xs text-destructive">{form.formState.errors.defaultBranch.message}</p>}</div><div><Label htmlFor="excluded-folders">Excluded folders</Label><Textarea id="excluded-folders" className="mt-2" {...form.register('excludedFolders')} /><p className="mt-1 text-xs text-muted-foreground">Comma-separated paths excluded from future automation.</p></div><Button type="submit" className="w-fit">Save preferences</Button></form></Card></AppShell> }
function PublicInfo({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <div className="min-h-screen bg-background"><header className="mx-auto flex min-h-20 max-w-6xl items-center justify-between px-5 sm:px-8"><Link to="/" className="font-display font-semibold">Auto<span className="text-primary">Git</span></Link><Link to="/" className="text-sm text-muted-foreground hover:text-foreground">Back home</Link></header><main className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><p className="font-mono text-xs uppercase tracking-[.18em] text-primary">{eyebrow}</p><h1 className="mt-4 max-w-3xl font-display text-4xl font-semibold tracking-tight sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{description}</p><div className="mt-12 grid gap-4 md:grid-cols-3">{children}</div></main></div> }
function InfoCard({ icon: Icon, title, text }: { icon: typeof Github; title: string; text: string }) { return <Card className="p-6"><div className="flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="size-5" /></div><h2 className="mt-5 font-display text-lg font-semibold">{title}</h2><p className="mt-2 leading-6 text-muted-foreground">{text}</p></Card> }
export function HelpPage() { return <PublicInfo eyebrow="Help & docs" title="A calmer path through the workspace." description="Understand what AutoGit currently supports, and which parts are still preview-only."><InfoCard icon={LifeBuoy} title="Connect GitHub" text="Use onboarding, then return to repositories to sync metadata." /><InfoCard icon={Workflow} title="Automation availability" text="Automation actions appear only after the execution service is connected." /><InfoCard icon={CircleHelp} title="Recover quickly" text="Retry a failed request, check your session, or return home." /></PublicInfo> }
export function AboutPage() { return <PublicInfo eyebrow="About AutoGit" title="A focused control center for the work you already do." description="AutoGit is designed around orientation: know what changed, what is connected, and what deserves your next ten minutes."><InfoCard icon={ShieldCheck} title="Private by default" text="Workspace data stays scoped to the authenticated account." /><InfoCard icon={Settings2} title="Explicit automation" text="Automation appears only when backed by a real execution service." /><InfoCard icon={Sparkles} title="Less noise" text="One primary action, useful empty states, and direct recovery paths." /></PublicInfo> }
export function NotFoundPage() { return <PublicInfo eyebrow="404" title="That route is not in the workspace." description="The page may have moved, or the link may be stale. Use the navigation to find a safe way back."><InfoCard icon={ArrowLeft} title="Return home" text="Start again from the public workspace overview." /></PublicInfo> }

