import { useState, type ReactNode } from 'react'
import { NavLink, useLocation } from 'react-router-dom'
import { Activity, Bell, BookOpen, Bot, ChevronLeft, ChevronRight, CircleHelp, GitBranch, LayoutDashboard, Menu, Search, Settings, UserRound, X } from 'lucide-react'
import { cn } from '@/lib/utils'

const nav = [{ to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard }, { to: '/repositories', label: 'Repositories', icon: GitBranch }, { to: '/automation', label: 'Automation', icon: Bot }, { to: '/analytics', label: 'Analytics', icon: Activity }, { to: '/activity', label: 'Activity', icon: BookOpen }, { to: '/notifications', label: 'Notifications', icon: Bell }]

function Logo() { return <NavLink to="/" className="flex items-center gap-3 font-display text-base font-semibold tracking-tight"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#238636] text-white shadow-[0_0_0_4px_rgba(35,134,54,.14)]"><GitBranch size={17} strokeWidth={2.4} /></span><span>Auto<span className="text-[#3fb950]">Git</span></span></NavLink> }

export function AppShell({ children }: { children: ReactNode }) {
  const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const location = useLocation()
  const sidebar = <aside className={cn('fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-[#30363D] bg-[#0D1117] p-4 transition-all lg:static lg:translate-x-0', collapsed && 'lg:w-[76px]', mobileOpen ? 'translate-x-0' : '-translate-x-full')}><div className="flex h-12 items-center justify-between px-2"><Logo /><button aria-label="Close menu" className="text-[#8B949E] lg:hidden" onClick={() => setMobileOpen(false)}><X size={20} /></button></div><nav className="mt-6 flex-1 space-y-1" aria-label="Primary navigation">{nav.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} onClick={() => setMobileOpen(false)} className={({ isActive }) => cn('flex h-10 items-center gap-3 rounded-lg px-3 text-sm font-medium transition-colors', isActive ? 'bg-[#238636]/15 text-[#F0F6FC]' : 'text-[#8B949E] hover:bg-[#161B22] hover:text-[#F0F6FC]', collapsed && 'lg:justify-center lg:px-0')}><Icon size={17} /><span className={cn(collapsed && 'lg:hidden')}>{label}</span>{label === 'Notifications' && <span className={cn('ml-auto h-1.5 w-1.5 rounded-full bg-[#58A6FF]', collapsed && 'lg:hidden')} />}</NavLink>)}<div className="my-5 border-t border-[#30363D]" />{[{ to: '/settings', label: 'Settings', icon: Settings }, { to: '/help', label: 'Help & docs', icon: CircleHelp }].map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} onClick={() => setMobileOpen(false)} className={({ isActive }) => cn('flex h-10 items-center gap-3 rounded-lg px-3 text-sm font-medium transition-colors', isActive ? 'bg-[#238636]/15 text-[#F0F6FC]' : 'text-[#8B949E] hover:bg-[#161B22] hover:text-[#F0F6FC]', collapsed && 'lg:justify-center lg:px-0')}><Icon size={17} /><span className={cn(collapsed && 'lg:hidden')}>{label}</span></NavLink>)}</nav><button onClick={() => setCollapsed(!collapsed)} className="hidden h-10 items-center justify-center rounded-lg text-[#8B949E] hover:bg-[#161B22] hover:text-white lg:flex" aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>{collapsed ? <ChevronRight size={18} /> : <ChevronLeft size={18} />}</button></aside>
  return <div className="min-h-screen bg-[#0D1117]">{mobileOpen && <button aria-label="Close navigation" className="fixed inset-0 z-30 bg-black/60 lg:hidden" onClick={() => setMobileOpen(false)} />}<div className="flex min-h-screen">{sidebar}<div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-[#30363D]/80 bg-[#0D1117]/95 px-4 backdrop-blur-md sm:px-6"><button className="rounded-lg p-2 text-[#8B949E] hover:bg-[#161B22] lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><div className="hidden items-center gap-2 text-sm text-[#8B949E] sm:flex"><span className="text-[#F0F6FC]">{location.pathname === '/dashboard' ? 'Workspace' : 'AutoGit'}</span><span>/</span><span className="capitalize">{location.pathname.split('/')[1] || 'home'}</span></div><div className="ml-auto flex items-center gap-2"><button className="hidden h-9 items-center gap-2 rounded-lg border border-[#30363D] px-3 text-sm text-[#8B949E] hover:bg-[#161B22] hover:text-white md:flex" aria-label="Search"><Search size={16} /> Search <kbd className="rounded border border-[#30363D] px-1.5 py-0.5 font-mono text-[10px]">⌘ K</kbd></button><NavLink to="/notifications" className="flex h-9 w-9 items-center justify-center rounded-lg text-[#8B949E] hover:bg-[#161B22] hover:text-white" aria-label="Notifications"><Bell size={18} /></NavLink><NavLink to="/profile" className="flex h-9 w-9 items-center justify-center rounded-lg border border-[#30363D] bg-[#161B22] text-[#8B949E] hover:text-white" aria-label="Profile"><UserRound size={17} /></NavLink></div></header><main className="mx-auto max-w-[1440px] p-5 sm:p-8">{children}</main></div></div></div>
}


