import { useState, type ReactNode } from 'react'
import { NavLink, useLocation } from 'react-router-dom'
import { Bell, BookOpen, Bot, ChevronLeft, ChevronRight, CircleHelp, GitBranch, LayoutDashboard, Menu, Search, Settings, UserRound, X, BarChart3 } from 'lucide-react'
import { cn } from '@/lib/utils'

const nav = [{ to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard }, { to: '/repositories', label: 'Repositories', icon: GitBranch }, { to: '/automation', label: 'Automation', icon: Bot }, { to: '/analytics', label: 'Analytics', icon: BarChart3 }, { to: '/activity', label: 'Activity', icon: BookOpen }, { to: '/notifications', label: 'Notifications', icon: Bell }]
function Logo() { return <NavLink to="/" className="flex items-center gap-3 font-display text-base font-semibold tracking-tight"><span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><GitBranch /></span><span>Auto<span className="text-primary">Git</span></span></NavLink> }

export function AppShell({ children }: { children: ReactNode }) {
  const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const location = useLocation()
  const itemClass = ({ isActive }: { isActive: boolean }) => cn('flex h-10 items-center gap-3 rounded-lg px-3 text-sm font-medium transition-colors', isActive ? 'bg-primary/10 text-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground', collapsed && 'lg:justify-center lg:px-0')
  const sidebar = <aside className={cn('fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-border bg-card p-4 transition-all lg:static lg:translate-x-0', collapsed && 'lg:w-[76px]', mobileOpen ? 'translate-x-0' : '-translate-x-full')}><div className="flex h-12 items-center justify-between px-2"><Logo /><button aria-label="Close menu" className="text-muted-foreground lg:hidden" onClick={() => setMobileOpen(false)}><X /></button></div><nav className="mt-6 flex flex-1 flex-col gap-1" aria-label="Primary navigation">{nav.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} onClick={() => setMobileOpen(false)} className={itemClass}><Icon /><span className={cn(collapsed && 'lg:hidden')}>{label}</span></NavLink>)}<div className="my-5 border-t border-border" />{[{ to: '/settings', label: 'Settings', icon: Settings }, { to: '/help', label: 'Help & docs', icon: CircleHelp }].map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} onClick={() => setMobileOpen(false)} className={itemClass}><Icon /><span className={cn(collapsed && 'lg:hidden')}>{label}</span></NavLink>)}</nav><button onClick={() => setCollapsed(!collapsed)} className="hidden h-10 items-center justify-center rounded-lg text-muted-foreground hover:bg-muted hover:text-foreground lg:flex" aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>{collapsed ? <ChevronRight /> : <ChevronLeft />}</button></aside>
  return <div className="min-h-screen bg-background">{mobileOpen && <button aria-label="Close navigation" className="fixed inset-0 z-30 bg-slate-900/10 lg:hidden" onClick={() => setMobileOpen(false)} />}<div className="flex min-h-screen">{sidebar}<div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-border bg-background/95 px-4 backdrop-blur-md sm:px-6"><button className="rounded-lg p-2 text-muted-foreground hover:bg-muted lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu /></button><div className="hidden items-center gap-2 text-sm text-muted-foreground sm:flex"><span className="text-foreground">{location.pathname === '/dashboard' ? 'Workspace' : 'AutoGit'}</span><span>/</span><span className="capitalize">{location.pathname.split('/')[1] || 'home'}</span></div><div className="ml-auto flex items-center gap-2"><button className="hidden h-9 items-center gap-2 rounded-lg border border-border px-3 text-sm text-muted-foreground hover:bg-muted md:flex" aria-label="Search"><Search /> Search <kbd className="rounded border border-border px-1.5 py-0.5 font-mono text-[10px]">⌘ K</kbd></button><NavLink to="/notifications" className="flex size-9 items-center justify-center rounded-lg text-muted-foreground hover:bg-muted" aria-label="Notifications"><Bell /></NavLink><NavLink to="/profile" className="flex size-9 items-center justify-center rounded-lg border border-border bg-card text-muted-foreground hover:text-foreground" aria-label="Profile"><UserRound /></NavLink></div></header><main className="mx-auto max-w-[1440px] p-5 sm:p-8">{children}</main></div></div></div>
}

