import { useState } from 'react'
import { motion, useReducedMotion } from 'motion/react'
import CountUp from 'react-countup'
import { Activity, ArrowRight, Bot, CircleDot, Code2, Command, GitBranch, Github, Network, Orbit, ShieldCheck, Sparkles, Workflow } from 'lucide-react'
import { Link } from 'react-router-dom'
import { WorkflowScene } from '@/components/workflow-scene'

const steps = [
  { icon: Github, name: 'Connect repository', detail: 'Authorize the projects you choose.' },
  { icon: Network, name: 'Analyze the signal', detail: 'Read branches, changes, and health.' },
  { icon: Sparkles, name: 'Generate next action', detail: 'Get a clear, useful recommendation.' },
  { icon: GitBranch, name: 'Review and push', detail: 'Keep the final decision human.' },
]

export function PremiumLanding() {
  const reduceMotion = useReducedMotion()
  return <main>
    <section className="relative min-h-[720px] overflow-hidden border-y border-white/10">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_40%,rgba(125,211,252,.12),transparent_32%),radial-gradient(circle_at_18%_70%,rgba(167,139,250,.10),transparent_28%),linear-gradient(115deg,#07090e_0%,#0b1019_48%,#111828_100%)]" />
      <div className="relative mx-auto grid min-h-[720px] max-w-7xl items-center px-5 pb-16 pt-12 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:pb-20 lg:pt-20">
        <motion.div initial={reduceMotion ? false : { opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }} className="relative z-10 max-w-2xl">
          <div className="flex items-center gap-3 text-xs font-mono uppercase tracking-[.22em] text-sky-100/55"><span className="size-2 rounded-full bg-cyan-300 shadow-[0_0_18px_#67e8f9]" />Repository operating system</div>
          <h1 className="mt-7 font-display text-6xl font-semibold leading-[.9] tracking-[-.075em] text-white sm:text-8xl">Keep the work<br /><span className="text-white/35">in motion.</span></h1>
          <p className="mt-7 max-w-lg text-base leading-7 text-white/60 sm:text-lg">AutoGit turns repository signals into a clear sequence of decisions, so your next commit is easier to see.</p>
          <div className="mt-9 flex flex-col gap-4 sm:flex-row sm:items-center"><motion.div whileHover={reduceMotion ? undefined : { scale: 1.03 }} whileTap={{ scale: .97 }}><Link to="/signup" className="inline-flex h-12 items-center justify-center gap-3 rounded-full bg-white px-6 text-sm font-semibold text-black">Continue with GitHub <ArrowRight className="size-4" /></Link></motion.div><a href="#workflow" className="inline-flex items-center gap-2 text-sm font-medium text-white/55 hover:text-white">See the workflow <ArrowRight className="size-4" /></a></div>
          <div className="mt-12 flex gap-8 border-t border-white/10 pt-5 text-xs text-white/40"><span>01 / connect</span><span>02 / inspect</span><span>03 / move</span></div>
        </motion.div>
        <div className="absolute -right-[12%] top-[8%] h-[620px] w-[75%] opacity-95 lg:relative lg:right-auto lg:top-auto lg:h-[660px] lg:w-full"><WorkflowScene reducedMotion={reduceMotion ?? false} /></div>
      </div>
    </section>
    <section className="border-b border-white/10 bg-[#0b1019] px-5 py-16 sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 sm:grid-cols-3"><Metric value={48} suffix="m" label="saved per developer, weekly" /><Metric value={3} suffix="×" label="fewer context switches" /><Metric value={99.9} suffix="%" decimals={1} label="automation visibility" /></div></section>
    <section className="border-b border-white/10 bg-[#0d1320] px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-mono uppercase tracking-[.22em] text-cyan-100/40">The premise</p><h2 className="mt-5 max-w-md font-display text-4xl font-semibold leading-tight tracking-[-.05em] text-white">A workflow for the space between commits.</h2></div><div className="grid gap-8 sm:grid-cols-3"><Signal icon={Network} title="See the system" text="Repositories, branches, and health signals in one view." /><Signal icon={Orbit} title="Choose the move" text="Turn loose signals into a clear next action." /><Signal icon={Sparkles} title="Keep momentum" text="Preview automation before it touches GitHub." /></div></div></section>
    <WorkflowDeck />
    <section className="bg-[#f5f7fb] px-5 py-24 text-[#101827] sm:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><p className="font-mono text-xs uppercase tracking-[.22em] text-slate-500">Repository universe</p><h2 className="mt-5 max-w-lg font-display text-5xl font-semibold leading-[.95] tracking-[-.06em]">Health, with a point of view.</h2><p className="mt-6 max-w-md text-lg leading-8 text-slate-600">One clear surface shows where to give attention—without making a developer read a dozen dashboards.</p><Link to="/dashboard" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold">Open workspace <ArrowRight className="size-4" /></Link></div><HealthPanel /></div></section>
    <section className="border-y border-white/10 bg-[#0b1019] px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[.22em] text-cyan-100/40">Automation engine</p><h2 className="mt-5 max-w-xl font-display text-5xl font-semibold leading-[.95] tracking-[-.06em] text-white">Make intent executable.</h2></div><Link to="/automation" className="inline-flex items-center gap-2 text-sm font-medium text-white/60 hover:text-white">Explore automation <ArrowRight className="size-4" /></Link></div><div className="mt-12 grid gap-3 md:grid-cols-3"><AutomationCard icon={Bot} title="AI commit briefs" text="Convert a focused diff into a readable commit message with the why intact." /><AutomationCard icon={Workflow} title="Preview before push" text="Every sequence is visible, reorderable, and safe to inspect first." /><AutomationCard icon={Activity} title="Watch the result" text="Follow branches, pull requests, and deployment signals in one trail." /></div></div></section>
    <section className="bg-[#eef2ff] px-5 py-24 text-[#101827] sm:px-8"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs uppercase tracking-[.22em] text-indigo-500">Built around developer momentum</p><div className="mt-5 grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><h2 className="font-display text-5xl font-semibold leading-[.95] tracking-[-.06em]">Your codebase is a living system. Treat it like one.</h2><div className="grid gap-4 sm:grid-cols-2"><UseCase icon={Code2} title="Solo builders" text="Keep a project’s next useful action close while you stay in flow." /><UseCase icon={Command} title="Product teams" text="Make asynchronous repository work understandable at a glance." /><UseCase icon={GitBranch} title="Platform teams" text="See cross-repository automation and health without chasing status." /><UseCase icon={ShieldCheck} title="Engineering leaders" text="Give people context and control without hiding side effects." /></div></div></div></section>
  </main>
}
function Metric({ value, suffix, label, decimals = 0 }: { value: number; suffix: string; label: string; decimals?: number }) { return <div className="border-l border-white/10 pl-5 first:border-l-0 sm:first:pl-0"><p className="font-display text-4xl font-semibold tracking-[-.06em] text-white"><CountUp end={value} decimals={decimals} duration={1.8} enableScrollSpy />{suffix}</p><p className="mt-2 text-sm text-white/45">{label}</p></div> }
function Signal({ icon: Icon, title, text }: { icon: typeof Network; title: string; text: string }) { return <div className="border-t border-white/15 pt-4"><Icon className="size-4 text-cyan-100/50" /><h3 className="mt-8 font-display text-lg font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-white/45">{text}</p></div> }
function WorkflowDeck() { const [active, setActive] = useState(0); const reduceMotion = useReducedMotion(); const item = steps[active]; const Icon = item.icon; return <section id="workflow" className="overflow-hidden bg-[#e7ecf4] px-5 py-24 text-[#101827] sm:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="font-mono text-xs uppercase tracking-[.22em] text-slate-500">Interactive workflow</p><h2 className="mt-5 max-w-md font-display text-5xl font-semibold leading-[.95] tracking-[-.06em]">The work, made tangible.</h2><p className="mt-6 max-w-md text-lg leading-8 text-slate-600">Move through the sequence. Each step makes the next one more confident.</p><div className="mt-9 grid gap-2">{steps.map((step, index) => <button key={step.name} onClick={() => setActive(index)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-medium ${active === index ? 'bg-white shadow-sm' : 'text-slate-500 hover:bg-white/55'}`}><span className={`flex size-7 items-center justify-center rounded-md ${active === index ? 'bg-slate-950 text-white' : 'bg-slate-300/50'}`}>{String(index + 1).padStart(2, '0')}</span>{step.name}</button>)}</div></div><div className="relative min-h-[420px]">{steps.map((step, index) => <motion.div key={step.name} animate={{ y: (index - active) * 19, x: (index - active) * 14, rotate: (index - active) * 1.4, opacity: index < active ? .22 : 1, scale: index === active ? 1 : .96, zIndex: 10 - index }} transition={reduceMotion ? { duration: 0 } : { type: 'spring', stiffness: 240, damping: 25 }} className="absolute inset-x-0 top-0 rounded-3xl border border-slate-200 bg-white p-8 shadow-[0_20px_60px_rgba(27,40,65,.14)] sm:p-10"><div className="flex items-center justify-between"><div className="flex size-12 items-center justify-center rounded-2xl bg-slate-950 text-white"><Icon className="size-5" /></div><span className="font-mono text-xs text-slate-400">STEP {String(active + 1).padStart(2, '0')} / 04</span></div><h3 className="mt-20 font-display text-4xl font-semibold tracking-[-.05em]">{item.name}</h3><p className="mt-4 max-w-sm text-lg leading-7 text-slate-600">{item.detail}</p><div className="mt-10 flex items-center gap-3 font-mono text-xs text-emerald-600"><CircleDot className="size-4" /> SIGNAL VERIFIED</div></motion.div>)}</div></div></section> }
function HealthPanel() { return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_20px_60px_rgba(27,40,65,.10)] sm:p-7"><div className="flex items-center justify-between"><div><p className="font-mono text-[11px] uppercase tracking-[.16em] text-slate-400">Workspace health</p><p className="mt-2 font-display text-2xl font-semibold">Steady, with two signals</p></div><div className="flex size-12 items-center justify-center rounded-full bg-emerald-100 font-mono text-sm font-semibold text-emerald-700">86</div></div><div className="mt-8 grid gap-3">{[['autogit/web', '96', 'Ready to merge'], ['platform/api', '78', '2 review requests'], ['design-system', '91', 'Deployment healthy']].map(([name, score, status]) => <div key={name} className="flex items-center gap-4 rounded-2xl bg-slate-50 p-4"><div className="flex size-9 items-center justify-center rounded-xl bg-white text-slate-700 shadow-sm"><Github className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{name}</p><p className="mt-1 text-xs text-slate-500">{status}</p></div><div className="w-20"><div className="h-1.5 overflow-hidden rounded-full bg-slate-200"><motion.div initial={{ width: 0 }} whileInView={{ width: `${score}%` }} className="h-full rounded-full bg-emerald-500" /></div><p className="mt-1 text-right font-mono text-[10px] text-slate-400">{score}/100</p></div></div>)}</div></div> }
function AutomationCard({ icon: Icon, title, text }: { icon: typeof Bot; title: string; text: string }) { return <motion.div whileHover={{ y: -5 }} className="rounded-2xl border border-white/10 bg-white/[.04] p-7"><Icon className="size-5 text-cyan-200" /><h3 className="mt-14 font-display text-xl font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-white/50">{text}</p></motion.div> }
function UseCase({ icon: Icon, title, text }: { icon: typeof Code2; title: string; text: string }) { return <div className="rounded-2xl border border-indigo-100 bg-white/70 p-6"><Icon className="size-5 text-indigo-600" /><h3 className="mt-10 font-display text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div> }