import type { ButtonHTMLAttributes, ReactNode } from 'react'
import { cn } from '@/lib/utils'

export function Button({ className, variant = 'primary', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'danger' }) {
  return <button className={cn('inline-flex h-10 items-center justify-center gap-2 rounded-lg px-4 text-sm font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#58A6FF] disabled:cursor-not-allowed disabled:opacity-50', { 'bg-[#238636] text-white hover:bg-[#2ea043]': variant === 'primary', 'border border-[#30363D] bg-[#161B22] text-[#F0F6FC] hover:bg-[#21262D]': variant === 'secondary', 'text-[#8B949E] hover:bg-[#161B22] hover:text-[#F0F6FC]': variant === 'ghost', 'bg-[#DA3633] text-white hover:bg-[#f85149]': variant === 'danger' }, className)} {...props} />
}

export function Card({ className, children }: { className?: string; children: ReactNode }) { return <section className={cn('rounded-xl border border-[#30363D] bg-[#161B22]', className)}>{children}</section> }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'success' | 'warning' | 'danger' | 'accent' }) { return <span className={cn('inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium', { 'border-[#30363D] text-[#8B949E]': tone === 'neutral', 'border-[#238636]/50 bg-[#238636]/10 text-[#3fb950]': tone === 'success', 'border-[#D29922]/50 bg-[#D29922]/10 text-[#D29922]': tone === 'warning', 'border-[#DA3633]/50 bg-[#DA3633]/10 text-[#f85149]': tone === 'danger', 'border-[#58A6FF]/50 bg-[#58A6FF]/10 text-[#58A6FF]': tone === 'accent' })}>{children}</span> }
export function Skeleton({ className }: { className?: string }) { return <div className={cn('animate-pulse rounded-md bg-[#21262D]', className)} aria-hidden="true" /> }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 font-mono text-xs uppercase tracking-[0.18em] text-[#58A6FF]">{eyebrow}</p><h1 className="font-display text-3xl font-semibold tracking-tight text-[#F0F6FC] sm:text-4xl">{title}</h1>{description && <p className="mt-3 max-w-2xl text-[#8B949E]">{description}</p>}</div>{action}</div> }
