import { useEffect, useState } from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import { Float, Line, PerspectiveCamera } from '@react-three/drei'
import * as THREE from 'three'

function Node({ position, size = 0.2, active = false }: { position: [number, number, number]; size?: number; active?: boolean }) { return <mesh position={position}><sphereGeometry args={[size, 24, 24]} /><meshStandardMaterial color={active ? '#f4f4f0' : '#777777'} emissive={active ? '#f4f4f0' : '#111111'} emissiveIntensity={active ? 0.35 : 0.05} roughness={0.35} metalness={0.8} /></mesh> }
function Core() { const ref = { current: null as THREE.Mesh | null }; useFrame((_, delta) => { if (ref.current) { ref.current.rotation.x += delta * 0.12; ref.current.rotation.y += delta * 0.2 } }); return <mesh ref={ref} position={[0, 0, 0]}><icosahedronGeometry args={[0.62, 2]} /><meshStandardMaterial color="#f4f4f0" wireframe roughness={0.2} metalness={0.85} /></mesh> }
function WorkflowObjects({ reducedMotion }: { reducedMotion: boolean }) { const nodes: [number, number, number][] = [[-2.25, 1.05, -0.25], [-2.45, -0.55, 0.1], [2.2, 0.85, -0.2], [2.35, -0.8, 0.25], [0.15, 1.65, -0.8]]; const paths = nodes.map((node) => [[0, 0, 0], node] as [[number, number, number], [number, number, number]]); return <group scale={reducedMotion ? 0.9 : 1}>{!reducedMotion && <Float speed={0.6} rotationIntensity={0.08} floatIntensity={0.15}><Core /></Float>}{reducedMotion && <Core />}{paths.map((path, index) => <Line key={index} points={path} color="#666666" lineWidth={0.8} transparent opacity={0.7} />)}{nodes.map((node, index) => <Node key={index} position={node} active={index === 0 || index === 2} />)}<mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -1.55, 0]}><circleGeometry args={[3.3, 64]} /><meshBasicMaterial color="#f4f4f0" transparent opacity={0.035} /></mesh></group> }
export function WorkflowScene({ reducedMotion = false }: { reducedMotion?: boolean }) { const [webgl, setWebgl] = useState(true); useEffect(() => { setWebgl(Boolean(window.WebGLRenderingContext)) }, []); if (!webgl) return <div aria-hidden="true" className="workflow-scene-fallback" />; return <div className="h-full min-h-[390px] w-full" aria-hidden="true"><Canvas dpr={[1, 1.6]} gl={{ antialias: true, alpha: true }}><PerspectiveCamera makeDefault position={[0, 0, 6.6]} fov={36} /><ambientLight intensity={0.55} /><directionalLight position={[3, 5, 4]} intensity={2.2} color="#ffffff" /><pointLight position={[-3, -2, 2]} intensity={4} color="#a8a8a8" /><WorkflowObjects reducedMotion={reducedMotion} /></Canvas></div> }
