import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'
import { AuthProvider } from '@/lib/auth'
import { Activity, Bell, CircleHelp, UserRound } from 'lucide-react'
import { DashboardPage, AuthPage, LandingPage, OnboardingPage, PlaceholderPage, ProtectedRoute, RepositoriesPage } from '@/pages'
import '@/styles.css'

function Protected({ children }: { children: React.ReactNode }) { return <ProtectedRoute>{children}</ProtectedRoute> }
createRoot(document.getElementById('root')!).render(<StrictMode><AuthProvider><BrowserRouter><Routes><Route path="/" element={<LandingPage />} /><Route path="/login" element={<AuthPage mode="login" />} /><Route path="/signup" element={<AuthPage mode="signup" />} /><Route path="/onboarding" element={<OnboardingPage />} /><Route path="/dashboard" element={<Protected><DashboardPage /></Protected>} /><Route path="/repositories" element={<Protected><RepositoriesPage /></Protected>} /><Route path="/profile" element={<Protected><PlaceholderPage title="Your profile" description="A focused view of your GitHub identity and contribution footprint." icon={UserRound} /></Protected>} /><Route path="/settings" element={<Protected><PlaceholderPage title="Settings" description="Control automation, account access, notifications, and workspace preferences." /></Protected>} /><Route path="/help" element={<PlaceholderPage title="Help & docs" description="Guides for connecting GitHub, managing repositories, and working with AutoGit." icon={CircleHelp} />} /><Route path="/about" element={<PlaceholderPage title="About AutoGit" description="A calm control center for the work you already do on GitHub." />} /><Route path="/notifications" element={<Protected><PlaceholderPage title="Notifications" description="Repository updates, sync results, and important workspace events." icon={Bell} /></Protected>} /><Route path="/analytics" element={<Protected><PlaceholderPage title="Analytics" description="Contribution patterns and repository signals will live here." icon={Activity} /></Protected>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></BrowserRouter></AuthProvider></StrictMode>)
